# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: doppeltHeldbesser
description: ""
author: "Niels Nübel"
baseurl: ""
url: "http://doppeltheldbesser.niels-nuebel.de"
googleanalyticss:  UA-123456789-1

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME, iframe]
sass:
  sass_dir: _sass
  style: compressed

repository: nielsnuebel/doppeltheldbesser


# Site nav
nav:

- name: Gewinnspiel
  link: "#Gameimg"
  src: "images/Button_Gewinnspiel.png"

- name: App
  link: "#applinks"
  src: "images/Button_App.png"

- name: Video
  link: "#Video"
  src: "images/Button_Videos.png"

- name: Games
  link: "#Games"
  src: "images/Button_Spiele.png"

- name: Galerie
  link: "#Galerie"
  src: "images/Button_Helden.png"